# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvexiCli < Formula
  desc "CLI tool to interact with Evexi API"
  homepage "https://evexi.technology/"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Darwin_arm64.tar.gz"
      sha256 "8bc2f1bbb83a24dcbb9e429c64935ecd4afe1dbb4f4172415daf895dc13b5a67"

      def install
        bin.install "evexi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Darwin_x86_64.tar.gz"
      sha256 "df4040238ff25cc11344ebc13056f1a8f815dbc79541186427c9c24621b06124"

      def install
        bin.install "evexi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Linux_arm64.tar.gz"
      sha256 "6da4be6666f1682537813211d6f4a61c29d10aa2b57ceb1a5db96fb519d62a26"

      def install
        bin.install "evexi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Linux_x86_64.tar.gz"
      sha256 "e6eaebd6fb8c551de28ae1d64687303706be0c731a7c2b9d12d155ea680171c5"

      def install
        bin.install "evexi"
      end
    end
  end
end
