# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvexiCli < Formula
  desc "CLI tool to interact with Evexi API"
  homepage "https://evexi.technology/"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Darwin_arm64.tar.gz"
      sha256 "341765c78173b005b3a56fc547fe387ea89cdcd439a1fb692e6fbfb5d2cfb849"

      def install
        bin.install "evexi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Darwin_x86_64.tar.gz"
      sha256 "ee6e295d10898a8284a73584f84cbdc1683a9db8503be0eeda48500e3c86e59c"

      def install
        bin.install "evexi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Linux_arm64.tar.gz"
      sha256 "a8b740b30a5943390bf22b446e04765494295ca543dafb61896a6aa397ad481f"

      def install
        bin.install "evexi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Evexi/evexi-cli/releases/download/0.0.2/evexi-cli_Linux_x86_64.tar.gz"
      sha256 "c172c5405ab2d57e58955beb5358ff92e70bbe3aeb7db031721eb09bed22ca59"

      def install
        bin.install "evexi"
      end
    end
  end
end
